import { Layers, ShoppingCart, Star, Megaphone, Quote, ChevronDown } from 'lucide-react';

export const sections = {
    name: 'Phần',
    subCategories: [
        {
            id: 'standard-sections',
            name: 'Phần tiêu chuẩn',
            lucideIcon: Layers,
            templates: [
                {
                    id: 'hero-section',
                    name: 'Phần tiêu đề chính',
                    lucideIcon: Layers,
                    description: 'Phần tiêu đề nổi bật cho trang đích',
                    previewImage: 'https://res.cloudinary.com/your_cloud_name/image/upload/v1234567890/hero-section.jpg',
                    json: {
                        type: 'section',
                        componentData: {
                            structure: 'ladi-standard',
                            title: 'Chào mừng đến với trang của chúng tôi',
                            backgroundColor: '#ffffff',
                            dataSource: { type: 'static' },
                            events: { onClick: { type: 'navigate', url: '/home' } },
                        },
                        size: { width: 420, height: 574 },
                        styles: { color: '#ffffff', textAlign: 'center' },
                        children: [
                            {
                                id: 'hero-heading',
                                type: 'heading',
                                componentData: { content: 'Chào mừng đến với trang của chúng tôi', title: 'Tiêu đề chính', dataSource: { type: 'static' } },
                                size: { width: 300, height: 50 },
                                position: { desktop: { x: 60, y: 50 }, tablet: { x: 60, y: 50 }, mobile: { x: 30, y: 30 } },
                                styles: { fontSize: '2rem', color: '#1f2937' },
                            },
                            {
                                id: 'hero-button',
                                type: 'button',
                                componentData: { content: 'Bắt đầu ngay', title: 'Nút bắt đầu', dataSource: { type: 'static' }, events: { onClick: { type: 'navigate', url: '/signup' } } },
                                size: { width: 150, height: 40 },
                                position: { desktop: { x: 135, y: 120 }, tablet: { x: 135, y: 120 }, mobile: { x: 80, y: 80 } },
                                styles: { background: '#2563eb', color: '#fff', borderRadius: '8px' },
                            },
                        ],
                    },
                },
                {
                    id: 'feature-section',
                    name: 'Phần tính năng',
                    lucideIcon: Star,
                    description: 'Giới thiệu các tính năng hoặc dịch vụ',
                    previewImage: 'https://res.cloudinary.com/your_cloud_name/image/upload/v1234567890/feature-section.jpg',
                    json: {
                        type: 'section',
                        componentData: {
                            structure: 'ladi-standard',
                            title: 'Tính năng của chúng tôi',
                            backgroundColor: '#f9fafb',
                            dataSource: { type: 'static' },
                            events: {},
                        },
                        size: { width: 420, height: 600 },
                        styles: { textAlign: 'center', padding: '40px 0' },
                        children: [
                            {
                                id: 'feature-heading',
                                type: 'heading',
                                componentData: { content: 'Tính năng nổi bật', title: 'Tiêu đề tính năng', dataSource: { type: 'static' } },
                                size: { width: 300, height: 50 },
                                position: { desktop: { x: 60, y: 20 }, tablet: { x: 60, y: 20 }, mobile: { x: 30, y: 20 } },
                                styles: { fontSize: '2rem', color: '#1f2937' },
                            },
                            {
                                id: 'feature-card-1',
                                type: 'card',
                                componentData: { title: 'Tính năng 1', content: 'Mô tả tính năng 1', dataSource: { type: 'static' } },
                                size: { width: 180, height: 200 },
                                position: { desktop: { x: 20, y: 100 }, tablet: { x: 20, y: 100 }, mobile: { x: 20, y: 100 } },
                                styles: { background: '#ffffff', borderRadius: '8px', boxShadow: '0 2px 8px rgba(0,0,0,0.1)' },
                            },
                            {
                                id: 'feature-card-2',
                                type: 'card',
                                componentData: { title: 'Tính năng 2', content: 'Mô tả tính năng 2', dataSource: { type: 'static' } },
                                size: { width: 180, height: 200 },
                                position: { desktop: { x: 220, y: 100 }, tablet: { x: 220, y: 100 }, mobile: { x: 20, y: 320 } },
                                styles: { background: '#ffffff', borderRadius: '8px', boxShadow: '0 2px 8px rgba(0,0,0,0.1)' },
                            },
                        ],
                    },
                },
                {
                    id: 'cta-section',
                    name: 'Phần kêu gọi hành động',
                    lucideIcon: Megaphone,
                    description: 'Khuyến khích người dùng hành động',
                    previewImage: 'https://res.cloudinary.com/your_cloud_name/image/upload/v1234567890/cta-section.jpg',
                    json: {
                        type: 'section',
                        componentData: {
                            structure: 'ladi-standard',
                            title: 'Sẵn sàng bắt đầu?',
                            backgroundColor: '#2563eb',
                            dataSource: { type: 'static' },
                            events: {},
                        },
                        size: { width: 420, height: 300 },
                        styles: { color: '#ffffff', textAlign: 'center', padding: '40px 0' },
                        children: [
                            {
                                id: 'cta-heading',
                                type: 'heading',
                                componentData: { content: 'Bắt đầu ngay hôm nay!', title: 'Tiêu đề kêu gọi', dataSource: { type: 'static' } },
                                size: { width: 300, height: 50 },
                                position: { desktop: { x: 60, y: 20 }, tablet: { x: 60, y: 20 }, mobile: { x: 30, y: 20 } },
                                styles: { fontSize: '2rem', color: '#ffffff' },
                            },
                            {
                                id: 'cta-button',
                                type: 'button',
                                componentData: { content: 'Đăng ký ngay', title: 'Nút đăng ký', dataSource: { type: 'static' }, events: { onClick: { type: 'navigate', url: '/signup' } } },
                                size: { width: 150, height: 40 },
                                position: { desktop: { x: 135, y: 100 }, tablet: { x: 135, y: 100 }, mobile: { x: 80, y: 100 } },
                                styles: { background: '#ffffff', color: '#2563eb', borderRadius: '8px' },
                            },
                        ],
                    },
                },
                {
                    id: 'testimonial-section',
                    name: 'Phần đánh giá',
                    lucideIcon: Quote,
                    description: 'Hiển thị đánh giá từ khách hàng',
                    previewImage: 'https://res.cloudinary.com/your_cloud_name/image/upload/v1234567890/testimonial-section.jpg',
                    json: {
                        type: 'section',
                        componentData: {
                            structure: 'ladi-standard',
                            title: 'Khách hàng nói gì',
                            backgroundColor: '#ffffff',
                            dataSource: { type: 'static' },
                            events: {},
                        },
                        size: { width: 420, height: 400 },
                        styles: { textAlign: 'center', padding: '40px 0' },
                        children: [
                            {
                                id: 'testimonial-heading',
                                type: 'heading',
                                componentData: { content: 'Đánh giá khách hàng', title: 'Tiêu đề đánh giá', dataSource: { type: 'static' } },
                                size: { width: 300, height: 50 },
                                position: { desktop: { x: 60, y: 20 }, tablet: { x: 60, y: 20 }, mobile: { x: 30, y: 20 } },
                                styles: { fontSize: '2rem', color: '#1f2937' },
                            },
                            {
                                id: 'testimonial-1',
                                type: 'testimonial',
                                componentData: { quote: 'Sản phẩm và dịch vụ tuyệt vời!', title: 'Đánh giá 1', author: 'Nguyễn Văn A', dataSource: { type: 'static' } },
                                size: { width: 380, height: 150 },
                                position: { desktop: { x: 20, y: 100 }, tablet: { x: 20, y: 100 }, mobile: { x: 20, y: 100 } },
                                styles: { background: '#f9fafb', borderRadius: '8px', padding: '16px' },
                            },
                        ],
                    },
                },
                {
                    id: 'footer-section',
                    name: 'Phần chân trang',
                    lucideIcon: ChevronDown,
                    description: 'Chân trang với liên kết và thông tin liên hệ',
                    previewImage: 'https://res.cloudinary.com/your_cloud_name/image/upload/v1234567890/footer-section.jpg',
                    json: {
                        type: 'section',
                        componentData: {
                            structure: 'ladi-standard',
                            title: 'Chân trang',
                            backgroundColor: '#1f2937',
                            dataSource: { type: 'static' },
                            events: {},
                        },
                        size: { width: 420, height: 200 },
                        styles: { color: '#ffffff', textAlign: 'center', padding: '40px 0' },
                        children: [
                            {
                                id: 'footer-menu',
                                type: 'menu',
                                componentData: {
                                    title: 'Menu chân trang',
                                    items: [
                                        { label: 'Trang chủ', url: '/home' },
                                        { label: 'Liên hệ', url: '/contact' },
                                        { label: 'Giới thiệu', url: '/about' },
                                    ],
                                    dataSource: { type: 'static' },
                                },
                                size: { width: 300, height: 50 },
                                position: { desktop: { x: 60, y: 20 }, tablet: { x: 60, y: 20 }, mobile: { x: 30, y: 20 } },
                                styles: { display: 'flex', gap: '20px', color: '#ffffff' },
                            },
                            {
                                id: 'footer-text',
                                type: 'paragraph',
                                componentData: { content: '© 2025 Công ty của bạn. Mọi quyền được bảo lưu.', title: 'Văn bản chân trang', dataSource: { type: 'static' } },
                                size: { width: 300, height: 30 },
                                position: { desktop: { x: 60, y: 80 }, tablet: { x: 60, y: 80 }, mobile: { x: 30, y: 80 } },
                                styles: { fontSize: '0.9rem', color: '#d1d5db' },
                            },
                        ],
                    },
                },
            ],
        },
        {
            id: 'ecommerce-sections',
            name: 'Phần thương mại điện tử',
            lucideIcon: ShoppingCart,
            templates: [
                {
                    id: 'product-showcase',
                    name: 'Trưng bày sản phẩm',
                    lucideIcon: ShoppingCart,
                    description: 'Hiển thị sản phẩm dạng lưới',
                    previewImage: 'https://res.cloudinary.com/your_cloud_name/image/upload/v1234567890/product-showcase.jpg',
                    json: {
                        type: 'section',
                        componentData: {
                            structure: 'ladi-standard',
                            title: 'Sản phẩm của chúng tôi',
                            backgroundColor: '#ffffff',
                            dataSource: { type: 'static' },
                            events: {},
                        },
                        size: { width: 420, height: 600 },
                        styles: { textAlign: 'center', padding: '40px 0' },
                        children: [
                            {
                                id: 'product-heading',
                                type: 'heading',
                                componentData: { content: 'Khám phá sản phẩm', title: 'Tiêu đề sản phẩm', dataSource: { type: 'static' } },
                                size: { width: 300, height: 50 },
                                position: { desktop: { x: 60, y: 20 }, tablet: { x: 60, y: 20 }, mobile: { x: 30, y: 20 } },
                                styles: { fontSize: '2rem', color: '#1f2937' },
                            },
                            {
                                id: 'product-grid',
                                type: 'grid',
                                componentData: {
                                    title: 'Lưới sản phẩm',
                                    columns: 2,
                                    items: [
                                        { title: 'Sản phẩm 1', image: 'https://res.cloudinary.com/your_cloud_name/image/upload/v1234567890/product1.jpg', price: '$29.99' },
                                        { title: 'Sản phẩm 2', image: 'https://res.cloudinary.com/your_cloud_name/image/upload/v1234567890/product2.jpg', price: '$39.99' },
                                    ],
                                    dataSource: { type: 'static' },
                                },
                                size: { width: 380, height: 400 },
                                position: { desktop: { x: 20, y: 100 }, tablet: { x: 20, y: 100 }, mobile: { x: 20, y: 100 } },
                                styles: { display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '20px' },
                            },
                        ],
                    },
                },
                {
                    id: 'cart-section',
                    name: 'Phần giỏ hàng',
                    lucideIcon: ShoppingCart,
                    description: 'Tổng quan giỏ hàng',
                    previewImage: 'https://res.cloudinary.com/your_cloud_name/image/upload/v1234567890/cart-section.jpg',
                    json: {
                        type: 'section',
                        componentData: {
                            structure: 'ladi-standard',
                            title: 'Giỏ hàng của bạn',
                            backgroundColor: '#ffffff',
                            dataSource: { type: 'state', stateKey: 'cartItems' },
                            events: {},
                        },
                        size: { width: 420, height: 400 },
                        styles: { textAlign: 'left', padding: '40px 0' },
                        children: [
                            {
                                id: 'cart-heading',
                                type: 'heading',
                                componentData: { content: 'Giỏ hàng', title: 'Tiêu đề giỏ hàng', dataSource: { type: 'static' } },
                                size: { width: 300, height: 50 },
                                position: { desktop: { x: 60, y: 20 }, tablet: { x: 60, y: 20 }, mobile: { x: 30, y: 20 } },
                                styles: { fontSize: '2rem', color: '#1f2937' },
                            },
                            {
                                id: 'cart-list',
                                type: 'list',
                                componentData: { title: 'Danh sách giỏ hàng', items: [], dataSource: { type: 'state', stateKey: 'cartItems' } },
                                size: { width: 380, height: 300 },
                                position: { desktop: { x: 20, y: 80 }, tablet: { x: 20, y: 80 }, mobile: { x: 20, y: 80 } },
                                styles: { listStyleType: 'none', padding: '0' },
                            },
                        ],
                    },
                },
            ],
        },
    ],
};